[package]
name = "german-invoice"
version = "0.2.0"
compiler = "0.10.0"
entrypoint = "lib.typ"
repository = "https://github.com/erictapen/typst-invoice"
authors = ["Kerstin Humm <@erictapen>"]
license = "GPL-3.0-or-later"
description = ""
keywords = []
categories = []
disciplines = []

[template]
path = "template"
entrypoint = "main.typ"
# thumbnail = "thumbnail.png"
